name = "encryptedcoins/encoins-core-aiken"
version = "1.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'encryptedcoins/encoins-core-aiken'"

[repository]
user = "encryptedcoins"
project = "encoins-core-aiken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
